# Generated by Django 4.2.6 on 2023-12-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='Topic_Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
