# Generated by Django 4.2.6 on 2023-12-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_webpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='Topic_name',
            new_name='Topic_Name',
        ),
    ]
